import {
  SquaresPlusIcon,
  ChartPieIcon,
  CursorArrowRaysIcon,
  FingerPrintIcon,
  BellIcon,
  BookmarkIcon,
  BriefcaseIcon,
  CalendarIcon,
  CameraIcon,
  ChatBubbleLeftIcon,
  CheckCircleIcon,
  ClockIcon,
  CloudIcon,
  CogIcon,
  CreditCardIcon,
  DocumentDuplicateIcon,
  ExclamationCircleIcon,
  EyeIcon,
  FlagIcon,
  GiftIcon,
  GlobeAltIcon,
  HeartIcon,
  HomeIcon,
  InboxIcon,
  InformationCircleIcon,
  KeyIcon,
  LightBulbIcon,
  LockClosedIcon,
  MagnifyingGlassIcon,
  MapIcon,
  PencilSquareIcon,
  PhoneIcon,
  ChartBarIcon,
} from "@heroicons/react/24/outline";

const iconClasses = "h-6 w-6 ";

export const availableIcons = {
  ChartPieIcon: <ChartBarIcon className={iconClasses} />,
  CursorArrowRaysIcon: <CursorArrowRaysIcon className={iconClasses} />,
  FingerPrintIcon: <FingerPrintIcon className={iconClasses} />,
  SquaresPlusIcon: <SquaresPlusIcon className={iconClasses} />,
  BellIcon: <BellIcon className={iconClasses} />,
  BookmarkIcon: <BookmarkIcon className={iconClasses} />,
  BriefcaseIcon: <BriefcaseIcon className={iconClasses} />,
  CalendarIcon: <CalendarIcon className={iconClasses} />,
  CameraIcon: <CameraIcon className={iconClasses} />,
  ChatBubbleLeftIcon: <ChatBubbleLeftIcon className={iconClasses} />,
  CheckCircleIcon: <CheckCircleIcon className={iconClasses} />,
  ClockIcon: <ClockIcon className={iconClasses} />,
  CloudIcon: <CloudIcon className={iconClasses} />,
  CogIcon: <CogIcon className={iconClasses} />,
  CreditCardIcon: <CreditCardIcon className={iconClasses} />,
  DocumentDuplicateIcon: <DocumentDuplicateIcon className={iconClasses} />,
  ExclamationCircleIcon: <ExclamationCircleIcon className={iconClasses} />,
  EyeIcon: <EyeIcon className={iconClasses} />,
  FlagIcon: <FlagIcon className={iconClasses} />,
  GiftIcon: <GiftIcon className={iconClasses} />,
  GlobeAltIcon: <GlobeAltIcon className={iconClasses} />,
  HeartIcon: <HeartIcon className={iconClasses} />,
  HomeIcon: <HomeIcon className={iconClasses} />,
  InboxIcon: <InboxIcon className={iconClasses} />,
  InformationCircleIcon: <InformationCircleIcon className={iconClasses} />,
  KeyIcon: <KeyIcon className={iconClasses} />,
  LightBulbIcon: <LightBulbIcon className={iconClasses} />,
  LockClosedIcon: <LockClosedIcon className={iconClasses} />,
  MagnifyingGlassIcon: <MagnifyingGlassIcon className={iconClasses} />,
  MapIcon: <MapIcon className={iconClasses} />,
  PencilSquareIcon: <PencilSquareIcon className={iconClasses} />,
  PhoneIcon: <PhoneIcon className={iconClasses} />,
};
