import {
    SquaresPlusIcon,
    ChartPieIcon,
    CursorArrowRaysIcon,
    FingerPrintIcon,
    BellIcon,
    BookmarkIcon,
    BriefcaseIcon,
    CalendarIcon,
    CameraIcon,
    ChatBubbleLeftIcon,
    CheckCircleIcon,
    ClockIcon,
    CloudIcon,
    CogIcon,
    CreditCardIcon,
    DocumentDuplicateIcon,
    ExclamationCircleIcon,
    EyeIcon,
    FlagIcon,
    GiftIcon,
    GlobeAltIcon,
    HeartIcon,
    HomeIcon,
    InboxIcon,
    InformationCircleIcon,
    KeyIcon,
    LightBulbIcon,
    LockClosedIcon,
    MagnifyingGlassIcon,
    MapIcon,
    PencilSquareIcon,
    PhoneIcon
  } from '@heroicons/react/24/outline';
  
export const availableIcons = [
    { icon: SquaresPlusIcon },
    { icon: ChartPieIcon },
    { icon: CursorArrowRaysIcon },
    { icon: FingerPrintIcon },
    { icon: BellIcon },
    { icon: BookmarkIcon },
    { icon: BriefcaseIcon },
    { icon: CalendarIcon },
    { icon: CameraIcon },
    { icon: ChatBubbleLeftIcon },
    { icon: CheckCircleIcon },
    { icon: ClockIcon },
    { icon: CloudIcon },
    { icon: CogIcon },
    { icon: CreditCardIcon },
    { icon: DocumentDuplicateIcon },
    { icon: ExclamationCircleIcon },
    { icon: EyeIcon },
    { icon: FlagIcon },
    { icon: GiftIcon },
    { icon: GlobeAltIcon },
    { icon: HeartIcon },
    { icon: HomeIcon },
    { icon: InboxIcon },
    { icon: InformationCircleIcon },
    { icon: KeyIcon },
    { icon: LightBulbIcon },
    { icon: LockClosedIcon },
    { icon: MagnifyingGlassIcon },
    { icon: MapIcon },
    { icon: PencilSquareIcon },
    { icon: PhoneIcon }
  ];
  